# NumPy 
- Numerical Python
- NumPy is the fundamental package for scientific computing in Python that provides (Open-Source)
- Library that provides a multidimensional array object, various derived objects(Universal standard for working with numerical data)
- and an assortment of routines for fast operations on arrays,
- including mathematical, 
- logical, shape manipulation,
- sorting, selecting, I/O, 
- discrete Fourier transforms, 
- basic linear algebra, 
- basic statistical operations, 
- random simulation and many more like them.

## NumPy Installation 
* conda install numpy- In command prompt
* pip install numpy - In VsCode
- Both of the above command can be used for installation 


###### LIST vs Numpy
- similar to list in shape 
- Faster than List
- less memory consumable
- Numpy works on same data type while list can work with different data type
- for short code list can be used

In [60]:
#list
aa=['islam','khan',1,2,3,2.4]
aa

['islam', 'khan', 1, 2, 3, 2.4]

In [59]:
#numpy
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [74]:
k=np.ones(5, dtype=np.int16)
k

array([1, 1, 1, 1, 1], dtype=int16)

In [73]:
k=np.ones(5, dtype=np.int8)
k

array([1, 1, 1, 1, 1], dtype=int8)

In [75]:
k=np.ones(5, dtype=np.int32)
k

array([1, 1, 1, 1, 1])

In [61]:
type(aa)

list

### Statring with our first line of code in numpy
- the first step is to import the numpy library 
- let gets started with an example

In [2]:
#Importing the numpy library
import numpy as np

#now we are going to print some number using numpy let's see how it works
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


- In the above example we just use a single of code to print first 10 positive integers

#### Array
- Array is a data structure which can store data of same data type like string, integer, float etc.
- 


In [10]:
#Example of an array
#array conataing names of my friends 
my_friends=np.array(['Sami khan','Amir', ' Xeshan','Fawad','Abdullah'])
my_friends

array(['Sami khan', 'Amir', ' Xeshan', 'Fawad', 'Abdullah'], dtype='<U9')

In [6]:
num=np.array([1,2,3,4,5,6])
num

array([1, 2, 3, 4, 5, 6])

##### Dimensions of  array
- 1D
- 2D
- 3D


In [11]:
#1Dimensional array
num=np.array([1,2,3,4,5,6])
num

array([1, 2, 3, 4, 5, 6])

In [12]:
#2Dimensional array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Tensors 
- 3D is known as tensor 

In [13]:
#3Dimensional array - tensor
N3_d= np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
N3_d


array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [78]:
#Assignment of making 3d array
assign_chilla=np.arange(24).reshape(3,4,2)
assign_chilla

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [72]:
N3_d[1:2:3]

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

- Arrays of different type using various function. 
- let's see few example


### Vector
- one dimensional array is known as Vector 


In [65]:
#vector
vector=np.array([1,2,3,4,5,6,7])
vector

array([1, 2, 3, 4, 5, 6, 7])

### matrix
- An array with two dimension is know as matrix

In [66]:
#matrix
matrix=np.array([[1,2,3,4,5],[6,7,8,9,0],[11,22,33,44,55]])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 22, 33, 44, 55]])

## Functions of an array

In [68]:
import numpy as np 
n=np.array([1,2,3,4,5])
n

array([1, 2, 3, 4, 5])

In [69]:
#array of zeros
zero_array= np.zeros(6)
zero_array

array([0., 0., 0., 0., 0., 0.])

In [20]:
#array of ones

one_array=np.ones(5) 
#(5) this argument specify how much time you want to print the one
one_array

array([1., 1., 1., 1., 1.])

In [70]:
len(a)

7

In [71]:
type(a)

numpy.ndarray

In [22]:
#empty array
empty_array=np.empty(2)
#it will produce an array with any random two numbers
empty_array

#your results can be differnt than this 

array([2.04710282e-110, 7.93104460e+212])

###### Arange function 
- with arange function one can create a range of elements
- with in arange we can also specify limits
- even, odd and many other let see with examples
- To do this, you will specify the first number, last number, and the step size.

In [23]:
#arange function
nums=np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [25]:
#Even numbers with arange function
even_nums= np.arange(2,20,2)
#specifiy starting from 2 to 20 with gap of 2
even_nums

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
#specifying odd numbers 
odd=np.arange(1,20,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
#multiples of 6
multiple_of_6= np.arange(6,100,6)
multiple_of_6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

###### linspace()
- linspace function print numbers that are equally spaced

In [30]:
#using lispace to print 8 nums btw 4 and 8 that are equally spaced
k=np.linspace(4, 8, num=8)
k

array([4.        , 4.57142857, 5.14285714, 5.71428571, 6.28571429,
       6.85714286, 7.42857143, 8.        ])

###### Soting an Array
- Adding, 
- removing, 
- sorting elements

In [34]:
#sorting first 20  numbers in accending order
arr_1 = np.array([2, 16, 5, 3,13, 17, 4,19, 6, 8,12,11,9,15,20,10,14,1,7,0,18])
np.sort(arr_1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

###### Desecnding order 
- there is no actual function but with the help of reverse() method we can reverse the sorted array to a different order. 

In [39]:
#bring the sorted array and apply the reverse method on that to print it in reversed order
arr_2=([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])
arr_2.reverse()
arr_2

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

# Adding
- with help of concatenate() function we can concatenate two arrays

In [46]:
#adding 2 arrays with the help of concatenate()
a = np.array([1, 2, 3, 4,0,11])
b = np.array([5, 6, 7, 8,9,10])

arr_3=np.concatenate((a,b))
#just to sort them as well we just asign it to a new variable
np.sort(arr_3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###### Sorting arrays in specific axis


In [3]:
#adding in a specific order Assignment
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

###### Shape, Size of an array 

In [4]:
arr_5 = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [5]:
np.transpose(arr_5)

array([[[0, 0, 0],
        [4, 4, 4]],

       [[1, 1, 1],
        [5, 5, 5]],

       [[2, 2, 2],
        [6, 6, 6]],

       [[3, 3, 3],
        [7, 7, 7]]])

In [50]:
#for dimension 
arr_5.ndim

3

In [52]:
#for shape
arr_5.shape

(3, 2, 4)

In [53]:
#for size
arr_5.size

24

###### Reshape
- the flexablilty of numpy that even you can reshape an array using reshape() function 

In [54]:
#working of reshape
arr_5 = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
arr_5.reshape(6,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [55]:
arr_5.reshape(12,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [57]:
#to make it a vector
arr_5.reshape(24)

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
       6, 7])

###### Indexing in Numpy

In [64]:
index_array=np.array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
       6, 7])
index_array[:23:3]

array([0, 3, 6, 1, 4, 7, 2, 5])

In [80]:
idx=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])
idx[:20:3]

array([ 0,  3,  6,  9, 12, 15, 18])

##### Creating array with sequence and other functions

In [81]:
a = np.array([127, 128, 129], dtype=np.int8)
a

array([ 127, -128, -127], dtype=int8)

In [82]:
a = np.array([127, 128, 129], dtype=np.int32)
a

array([127, 128, 129])

In [83]:
a = np.array([127, 128, 129], dtype=np.int16)
a

array([127, 128, 129], dtype=int16)

In [84]:
a=np.arange(2, 10, dtype=float)
a

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
#eye function to print identity 
a=np.eye(3)
a


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [90]:
a=np.eye(3,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [93]:
#diagnol matrix 
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [94]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [96]:
a=np.array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
np.diag(a)

array([0, 3])

In [97]:
#vander function
a=np.vander([1, 2, 3, 4], 2)
a

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [100]:
a=np.vander([1, 2, 2, 2], 4)
a

array([[1, 1, 1, 1],
       [8, 4, 2, 1],
       [8, 4, 2, 1],
       [8, 4, 2, 1]])